Fixed issue with audio settings
GhostEntity12/HouseHunting pull request #107
Opened 2023-09-24 05:29 UTC by GhostEntity12

Altered the AudioManager to fix some issues

2023-09-25 08:01 UTC, KS-103819380 requested changes
Could you change the opacity of settings canvas in main menu to be fully opaque for better UX?

2023-09-25 13:58 UTC, GhostEntity12 commented
Opacity increased, still slightly opaque for continuity. Would be good to get a modal box to use as a background but that's probably further down the line.

2023-09-26 10:09 UTC, KS-103819380 commented
I can merge into main once you have solved the merge conflicts

2023-09-27 03:56 UTC, KS-103819380 approved these changes

2023-09-27 03:56 UTC, merged