Sound manager
GhostEntity12/HouseHunting pull request #23
Opened 2023-05-15 03:42 UTC by SassDude

created audio manager prefab and interactions able to be done with the audio manager

2023-05-15 12:09 UTC, GhostEntity12 requested changes
Please ensure that the audio adheres to the [naming conventions](https://docs.google.com/document/d/1ngzQ6UUjyCyknk-3t2Rl_pwRQeF-trg98L_ouxy9t1c/edit#heading=h.1q0659lo19up) set out in the process document, and add some basic comments for readability and maintainability

2023-05-17 06:34 UTC, SassDude commented on Assets/Scripts/Managers/AudioManager.cs
> +            s.source.playOnAwake = s.playOnAwake;
good point, will do

2023-05-17 06:40 UTC, SassDude commented on Assets/Scripts/Managers/HuntingManager.cs
> +        audioManager[0].Play("Ambience");
in the case we don't want music or sound effects to be cut off by each scene 

2023-05-17 06:40 UTC, SassDude commented on Assets/Scripts/Managers/AudioManager.cs
> +        DontDestroyOnLoad(gameObject);
in the case we don't want music or sound effects to be cut off by each scene or restart 

2023-05-19 02:08 UTC, GhostEntity12 commented
Superseded by https://github.com/GhostEntity12/HouseHunting/pull/28 - Audio Manager

2023-05-19 02:08 UTC, closed without merging