Sprinting
GhostEntity12/HouseHunting pull request #52
Opened 2023-08-03 03:18 UTC by SassDude

Implemented Sprinting, Switched sprinting to be shift and crouching to be controlled and affect sound alerts 

2023-08-03 09:25 UTC, AdmiralSoviet requested changes
Can't approve, there's a bug. For some reason, the jump now launches the player into the stratosphere. if you fix this then i can approve : )

2023-08-04 06:03 UTC, GhostEntity12 commented
Merging of #57 also introduced merge conflicts that need to be resolved.

2023-08-06 06:49 UTC, SassDude commented
Fixed jump bug also added a sound event for it as was missing

2023-08-09 06:27 UTC, AdmiralSoviet approved these changes

2023-08-09 06:27 UTC, merged